<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>NoAutoExposure</RootNamespace>
    <AssemblyName>NoAutoExposure</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BeatSaberModdingTools.Tasks" Version="2.0.0-beta7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Menu\gameplayMenu.bsml" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BGLib.UnityExtension">
      <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\BGLib.UnityExtension.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BSML">
      <HintPath>$(GameDirectory)\Plugins\BSML.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="HMLib">
      <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\HMLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="HMRendering">
      <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\HMRendering.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Hive.Versioning">
      <HintPath>$(GameDirectory)\Libs\Hive.Versioning.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="IPA.Loader">
      <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\IPA.Loader.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Main">
      <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\Main.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Rendering">
      <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\Rendering.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SiraUtil">
      <HintPath>$(GameDirectory)\Plugins\SiraUtil.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SongCore">
      <HintPath>$(GameDirectory)\Plugins\SongCore.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Zenject">
      <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\Zenject.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Zenject-usage">
      <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\Zenject-usage.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
